{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "da95ce7b-3354-4dc7-8096-3bf7788b4f9d",
   "metadata": {},
   "outputs": [],
   "source": [
    "import streamlit as st\n",
    "from Bio.Seq import Seq\n",
    "from Bio.Blast import NCBIWWW, NCBIXML\n",
    "from Bio.Data import CodonTable\n",
    "\n",
    "def complement(dna_sequence):\n",
    "    \"\"\"\n",
    "    Retorna o complemento reverso da sequência de DNA.\n",
    "\n",
    "    Argumento:\n",
    "    - dna_sequence: sequência de DNA no formato 5' 3'\n",
    "\n",
    "    Retorna:\n",
    "    - Complemento reverso da sequência de DNA\n",
    "    \"\"\"\n",
    "    seq = Seq(dna_sequence)\n",
    "    return seq.complement()\n",
    "\n",
    "def translate(dna_sequence):\n",
    "    \"\"\"\n",
    "    Traduz a sequência de DNA em uma sequência de aminoácidos.\n",
    "\n",
    "    Argumento:\n",
    "    - dna_sequence: sequência de DNA no formato 5' 3'\n",
    "\n",
    "    Retorna:\n",
    "    - Sequência de aminoácidos traduzida\n",
    "    \"\"\"\n",
    "    seq = Seq(dna_sequence)\n",
    "    return seq.translate(table=11)  # Usando a tabela de códons padrão (tabela 11)\n",
    "\n",
    "def find_frames(dna_sequence):\n",
    "    \"\"\"\n",
    "    Encontra as sequências de RNA e aminoácidos para cada frame da sequência de DNA.\n",
    "\n",
    "    Argumento:\n",
    "    - dna_sequence: sequência de DNA no formato 5' 3'\n",
    "\n",
    "    Retorna:\n",
    "    - Dicionário contendo as sequências de RNA e aminoácidos para cada frame\n",
    "      no formato:\n",
    "      {\n",
    "        frame: {\n",
    "          'rna': sequência de RNA,\n",
    "          'aminoacidos': sequência de aminoácidos\n",
    "        },\n",
    "        ...\n",
    "      }\n",
    "    \"\"\"\n",
    "    seq = Seq(dna_sequence)\n",
    "    frames = {}\n",
    "    for frame in range(3):\n",
    "        rna_sequence = seq[frame:].transcribe()\n",
    "        aminoacid_sequence = rna_sequence.translate(table=11)\n",
    "        frames[frame + 1] = {\n",
    "            'rna': str(rna_sequence),\n",
    "            'aminoacidos': str(aminoacid_sequence)\n",
    "        }\n",
    "    return frames\n",
    "\n",
    "def blast_sequence(dna_sequence):\n",
    "    \"\"\"\n",
    "    Realiza uma pesquisa BLAST para encontrar sequências de nucleotídeos semelhantes.\n",
    "\n",
    "    Argumento:\n",
    "    - dna_sequence: sequência de DNA no formato 5' 3'\n",
    "\n",
    "    Retorna:\n",
    "    - Lista de resultados BLAST contendo o nome dos nucleotídeos semelhantes e o link para o BLAST correspondente\n",
    "    \"\"\"\n",
    "    result_handle = NCBIWWW.qblast('blastn', 'nt', dna_sequence)\n",
    "    blast_records = NCBIXML.parse(result_handle)\n",
    "    blast_results = []\n",
    "    for blast_record in blast_records:\n",
    "        for alignment in blast_record.alignments:\n",
    "            blast_results.append({\n",
    "                'nome': alignment.title,\n",
    "                'link': alignment.hit_id\n",
    "            })\n",
    "    return blast_results\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "332630de-83c8-49a3-8bdb-f8b45cb28f29",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2023-06-06 17:31:00.736 \n",
      "  \u001b[33m\u001b[1mWarning:\u001b[0m to view this Streamlit app on a browser, run it with the following\n",
      "  command:\n",
      "\n",
      "    streamlit run c:\\venv\\ilumpy\\lib\\site-packages\\ipykernel_launcher.py [ARGUMENTS]\n"
     ]
    }
   ],
   "source": [
    "def main():\n",
    "    st.title(\"protKAGG - Tradução e Síntese Protéica\")\n",
    "    st.write(\"Seu software de tradução e síntese protéica favorito!\")\n",
    "\n",
    "    dna_sequence = st.text_input(\"Digite a sequência de DNA no formato 5' 3'\")\n",
    "    dna_sequence = dna_sequence.replace(\" \", \"\")\n",
    "\n",
    "    preview_expander = st.expander(\"Preview\")\n",
    "    if preview_expander.button(\"Mostrar preview\"):\n",
    "        complemento = complement(dna_sequence)\n",
    "        st.write(\"Complemento Reverso:\", complemento)\n",
    "\n",
    "        aminoacidos = translate(dna_sequence)\n",
    "        st.write(\"Aminoácidos:\", aminoacidos)\n",
    "\n",
    "        frames = find_frames(dna_sequence)\n",
    "        for frame, data in frames.items():\n",
    "            st.write(f\"Frame {frame}:\")\n",
    "            st.write(\"RNA:\", data['rna'])\n",
    "            st.write(\"Aminoácidos:\", data['aminoacidos'])\n",
    "\n",
    "        blast_results = blast_sequence(dna_sequence)\n",
    "        st.write(\"\\nResultados do BLAST:\")\n",
    "        for result in blast_results:\n",
    "            st.write(\"Nome:\", result['nome'])\n",
    "            st.write(\"Link:\", result['link'])\n",
    "\n",
    "if __name__ == '__main__':\n",
    "    main()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "id": "36c628b9-7e20-4dbd-adb5-f053036572d9",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "'\\nGCTCCCGGCTTAGAGGACAGCGGGGAAGGCGGGCGGTGGGGCAGGGGGCCTGAAGCGGCGGTACCGGTGC\\nTGGCGGCGGCAGCTGAGGCCTTGGCCGAAGCCGCGCGAACCTCAGGGCAAGATGCTTGGAACCGGACCTG\\nCCGCCGCCACCACCGCTGCCACCACATCTAGCAATGTGAGCGTCCTGCAGCAGTTTGCCAGTGGCCTAAA\\nGAGCCGGAATGAGGAAACCAGGGCCAAAGCCGCCAAGGAGCTCCAGCACTATGTCACCATGGAACTCCGA\\nGAGATGAGTCAAGAGGAGTCTACTCGCTTCTATGACCAACTGAACCATCACATTTTTGAATTGGTTTCCA\\nGCTCAGATGCCAATGAGAGGAAAGGTGGCATCTTGGCCATAGCTAGCCTCATAGGAGTGGAAGGTGGGAA\\nTGCCACCCGAATTGGCAGATTTGCCAACTATCTTCGGAACCTCCTCCCCTCCAATGACCCAGTTGTCATG\\nGAAATGGCATCCAAGGCCATTGGCCGTCTTGCCATGGCAGGGGACACTTTTACCGCTGAGTACGTGGAAT\\nTTGAGGTGAAGCGAGCCCTGGAATGGCTGGGTGCTGACCGCAATGAGGGCCGGAGACATGCAGCTGTCCT\\nGGTTCTCCGTGAGCTGGCCATCAGCGTCCCTACCTTCTTCTTCCAGCAAGTGCAACCCTTCTTTGACAAC\\nATTTTTGTGGCCGTGTGGGACCCCAAACAGGCCATCCGTGAGGGAGCTGTAGCCGCCCTTCGTGCCTGTC\\nTGATTCTCACAACCCAGCGTGAGCCGAAGGAGATGCAGAAGCCTCAGTGGTACAGGCACACATTTGAAGA\\nAGCAGAGAAGGGATTTGATGAGACCTTGGCCAAAGAGAAGGGCATGAATCGGGATGATCGGATCCATGGA\\nGCCTTGTTGATCCTTAACGAGCTGGTCCGAATCAGCAGCATGGAGGGAGAGCGTCTGAGAGAAGAAATGG\\nAAGAAATCACACAGCAGCAGCTGGTACACGACAAGTACTGCAAAGATCTCATGGGCTTCGGAACAAAACC\\nTCGTCACATTACCCCCTTCACCAGTTTCCAGGCTGTACAGCCCCAGCAGTCAAATGCCTTGGTGGGGCTG\\nCTGGGGTACAGCTCTCACCAAGGCCTCATGGGATTTGGGACCTCCCCCAGTCCAGCTAAGTCCACCCTGG\\nTGGAGAGCCGGTGTTGCAGAGACTTGATGGAGGAGAAATTTGATCAGGTGTGCCAGTGGGTGCTGAAATG\\nCAGGAATAGCAAGAACTCGCTGATCCAAATGACAATCCTTAATTTGTTGCCCCGCTTGGCTGCATTCCGA\\nCCTTCTGCCTTCACAGATACCCAGTATCTCCAAGATACCATGAACCATGTCCTAAGCTGTGTCAAGAAGG\\nAGAAGGAACGTACAGCGGCCTTCCAAGCCCTGGGGCTACTTTCTGTGGCTGTGAGGTCTGAGTTTAAGG'"
      ]
     },
     "execution_count": 8,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "\"\"\"\n",
    "GCTCCCGGCTTAGAGGACAGCGGGGAAGGCGGGCGGTGGGGCAGGGGGCCTGAAGCGGCGGTACCGGTGC\n",
    "TGGCGGCGGCAGCTGAGGCCTTGGCCGAAGCCGCGCGAACCTCAGGGCAAGATGCTTGGAACCGGACCTG\n",
    "CCGCCGCCACCACCGCTGCCACCACATCTAGCAATGTGAGCGTCCTGCAGCAGTTTGCCAGTGGCCTAAA\n",
    "GAGCCGGAATGAGGAAACCAGGGCCAAAGCCGCCAAGGAGCTCCAGCACTATGTCACCATGGAACTCCGA\n",
    "GAGATGAGTCAAGAGGAGTCTACTCGCTTCTATGACCAACTGAACCATCACATTTTTGAATTGGTTTCCA\n",
    "GCTCAGATGCCAATGAGAGGAAAGGTGGCATCTTGGCCATAGCTAGCCTCATAGGAGTGGAAGGTGGGAA\n",
    "TGCCACCCGAATTGGCAGATTTGCCAACTATCTTCGGAACCTCCTCCCCTCCAATGACCCAGTTGTCATG\n",
    "GAAATGGCATCCAAGGCCATTGGCCGTCTTGCCATGGCAGGGGACACTTTTACCGCTGAGTACGTGGAAT\n",
    "TTGAGGTGAAGCGAGCCCTGGAATGGCTGGGTGCTGACCGCAATGAGGGCCGGAGACATGCAGCTGTCCT\n",
    "GGTTCTCCGTGAGCTGGCCATCAGCGTCCCTACCTTCTTCTTCCAGCAAGTGCAACCCTTCTTTGACAAC\n",
    "ATTTTTGTGGCCGTGTGGGACCCCAAACAGGCCATCCGTGAGGGAGCTGTAGCCGCCCTTCGTGCCTGTC\n",
    "TGATTCTCACAACCCAGCGTGAGCCGAAGGAGATGCAGAAGCCTCAGTGGTACAGGCACACATTTGAAGA\n",
    "AGCAGAGAAGGGATTTGATGAGACCTTGGCCAAAGAGAAGGGCATGAATCGGGATGATCGGATCCATGGA\n",
    "GCCTTGTTGATCCTTAACGAGCTGGTCCGAATCAGCAGCATGGAGGGAGAGCGTCTGAGAGAAGAAATGG\n",
    "AAGAAATCACACAGCAGCAGCTGGTACACGACAAGTACTGCAAAGATCTCATGGGCTTCGGAACAAAACC\n",
    "TCGTCACATTACCCCCTTCACCAGTTTCCAGGCTGTACAGCCCCAGCAGTCAAATGCCTTGGTGGGGCTG\n",
    "CTGGGGTACAGCTCTCACCAAGGCCTCATGGGATTTGGGACCTCCCCCAGTCCAGCTAAGTCCACCCTGG\n",
    "TGGAGAGCCGGTGTTGCAGAGACTTGATGGAGGAGAAATTTGATCAGGTGTGCCAGTGGGTGCTGAAATG\n",
    "CAGGAATAGCAAGAACTCGCTGATCCAAATGACAATCCTTAATTTGTTGCCCCGCTTGGCTGCATTCCGA\n",
    "CCTTCTGCCTTCACAGATACCCAGTATCTCCAAGATACCATGAACCATGTCCTAAGCTGTGTCAAGAAGG\n",
    "AGAAGGAACGTACAGCGGCCTTCCAAGCCCTGGGGCTACTTTCTGTGGCTGTGAGGTCTGAGTTTAAGG\"\"\""
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "c315ad62-0ffa-4556-8d53-6319774b62e8",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "ilumpy",
   "language": "python",
   "name": "ilumpy"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.8"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
